import { type AppType } from "next/app";
import { SignInButton, SignedIn, SignedOut, UserButton, ClerkProvider } from '@clerk/nextjs';
import { type FC } from 'react';
import Head from "next/head";

import { api } from "~/utils/api";
import "~/styles/globals.css";

const Navbar: FC = () => (
  <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header className='h-14 w-full fixed px-[15.8%] bg-slate-500 flex items-center justify-end drop-shadow-md border-b-[1px] border-b-slate-400'>
      <SignedOut><SignInButton /></SignedOut>
      <SignedIn><UserButton /></SignedIn>
    </header>
  </>
)

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider {...pageProps}>
      <Navbar />
      <Component {...pageProps} />
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
